name: 'ggm_dwh'
version: '1.0.0'
config-version: 2
profile: ggm_dwh

models:
  ggm-dwh:
    raw:
      +schema: raw
      +materialized: table
    stg:
      +schema: stg
      +materialized: view
    ggm:
      +schema: ggm  # All GGM models go to the `ggm` schema
      +materialized: table  # All models in ggm/Kern/RGBZ/ will be tables
    datamart:
      +schema: datamart
      +materialized: view